# This is a basic workflow to help you get started with Actions

name: multi

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 12 * * *' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MOOD_GOOD: "Happy"
      MOOD_BAD: "Sad"
      
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: "if mood good"
        if: env.MOOD_GOOD == 'Happy'
        run: echo "Joe is $MOOD_GOOD today!"
        
      - name: "if mood bad"
        if: env.MOOD_BAD == 'Sad'
        run: echo "Joe is $MOOD_BAD today!"
        
      - name: "neither" 
        if: env.MOOD_GOOD != 'Happy' && env.MOOD_BAD != 'Sad'
        run: echo "tell me which mood you are in"
      
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Final mood
        env:
          MOOD_NEITHER: ${{ secrets.MOOD_NEITHER }}
        if: env.MOOD_NEITHER != '' && env.MOOD_NEITHER == 'Hungry'
        run: echo "Joe is just $MOOD_NEITHER"
          
    
